name: daddy3d Development workflow
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SERVER_SECRET }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/vhosts/dev.daddy3d.com/
            git pull origin master 
            ls -l